/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ReviseRouteImport } from './routes/revise'
import { Route as QuestionBankRouteImport } from './routes/question-bank'
import { Route as MemoRouteImport } from './routes/memo'
import { Route as KnowledgeGraphRouteImport } from './routes/knowledge-graph'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviseRoute = ReviseRouteImport.update({
  id: '/revise',
  path: '/revise',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionBankRoute = QuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoRoute = MemoRouteImport.update({
  id: '/memo',
  path: '/memo',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeGraphRoute = KnowledgeGraphRouteImport.update({
  id: '/knowledge-graph',
  path: '/knowledge-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/memo': typeof MemoRoute
  '/question-bank': typeof QuestionBankRoute
  '/revise': typeof ReviseRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/memo': typeof MemoRoute
  '/question-bank': typeof QuestionBankRoute
  '/revise': typeof ReviseRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/memo': typeof MemoRoute
  '/question-bank': typeof QuestionBankRoute
  '/revise': typeof ReviseRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/knowledge-graph'
    | '/memo'
    | '/question-bank'
    | '/revise'
    | '/sign-in'
    | '/sign-up'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/knowledge-graph'
    | '/memo'
    | '/question-bank'
    | '/revise'
    | '/sign-in'
    | '/sign-up'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/knowledge-graph'
    | '/memo'
    | '/question-bank'
    | '/revise'
    | '/sign-in'
    | '/sign-up'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  MemoRoute: typeof MemoRoute
  QuestionBankRoute: typeof QuestionBankRoute
  ReviseRoute: typeof ReviseRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revise': {
      id: '/revise'
      path: '/revise'
      fullPath: '/revise'
      preLoaderRoute: typeof ReviseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-bank': {
      id: '/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof QuestionBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memo': {
      id: '/memo'
      path: '/memo'
      fullPath: '/memo'
      preLoaderRoute: typeof MemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-graph': {
      id: '/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/knowledge-graph'
      preLoaderRoute: typeof KnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  MemoRoute: MemoRoute,
  QuestionBankRoute: QuestionBankRoute,
  ReviseRoute: ReviseRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
